#!/usr/bin/env bash
# Rename all wheels in wheels_input/ to gtsam_extended with normalized version
set -euo pipefail
cd "$(dirname "$0")/.."
rm -rf renamed_wheels
python3 "$(dirname "$0")/../rename_wheel.py" "$@"
